-- MySQL Script generated by MySQL Workbench
-- Wed Sep  2 08:53:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sigcodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sigcodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sigcodb` DEFAULT CHARACTER SET utf8 ;
USE `sigcodb` ;

-- -----------------------------------------------------
-- Table `sigcodb`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Marca` (
  `codigo` VARCHAR(5) NOT NULL,
  `marca` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Familia` (
  `codigo` VARCHAR(5) NOT NULL,
  `familia` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Articulo` (
  `codigo` VARCHAR(10) NOT NULL,
  `CIP` VARCHAR(25) NULL COMMENT 'codigo interno del producto',
  `descripcion` VARCHAR(45) NULL,
  `especificacion` TEXT NULL,
  `fechaIngreso` DATE NULL,
  `precioCosto` DECIMAL(10,2) NULL,
  `precioVenta` DECIMAL(10,2) NULL,
  `codMarca` VARCHAR(5) NULL,
  `codFamilia` VARCHAR(5) NULL COMMENT 'unidad de medida',
  `activo` ENUM('N','S') NULL COMMENT '1 - Activo\n2 - Inactivo\nhabilitar este producto para venta',
  `foto` LONGBLOB NULL,
  `CodEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Personal` (
  `codigo` VARCHAR(10) NOT NULL,
  `fechaIngreso` DATE NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `edad` INT NULL,
  `direccion` VARCHAR(45) NULL,
  `ciRuc` VARCHAR(45) NULL,
  `telefono` VARCHAR(25) NULL,
  `salario` DECIMAL(10,2) NULL,
  `email` VARCHAR(250) NULL,
  `tipoPago` ENUM('E','C','T') NULL COMMENT 'E - Efectivo\nC - Cheque\nT- Transferencia',
  `codBanco` VARCHAR(5) NULL COMMENT 'banco en caso de pago a cheque',
  `sexo` ENUM('M','F') NULL,
  `estadoCivil` ENUM('C','S','D','V') NULL,
  `codDepartamento` VARCHAR(5) NULL,
  `codPais` VARCHAR(5) NULL,
  `codCiudad` VARCHAR(5) NULL,
  `codBarrio` VARCHAR(5) NULL,
  `casaNro` VARCHAR(10) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `codProfesion` VARCHAR(5) NULL,
  `foto` LONGBLOB NULL,
  `motivoBaja` VARCHAR(45) NULL,
  `estado` ENUM('A','B') NULL COMMENT 'A - Activo\nB- Dado de baja',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Cliente` (
  `codigo` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `fechaNac` DATE NULL,
  `fechaIng` DATE NULL COMMENT 'fecha de ingreso',
  `sexo` ENUM('M','F') NULL,
  `edad` INT NULL,
  `telefono` VARCHAR(25) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `codProfesion` VARCHAR(5) NULL,
  `email` VARCHAR(250) NULL,
  `codPais` VARCHAR(5) NULL,
  `codDepartamento` VARCHAR(5) NULL,
  `codCiudad` VARCHAR(5) NULL,
  `codBarrio` VARCHAR(5) NULL,
  `direccion` VARCHAR(45) NULL,
  `nroCasa` VARCHAR(10) NULL,
  `codCobrador` VARCHAR(5) NULL,
  `codVendedor` VARCHAR(5) NULL,
  `limiteCredito` DECIMAL(10,2) NULL,
  `estado` ENUM('A','I') NULL COMMENT 'A - ACTIVO\nI - INACTIVO',
  `obs` TEXT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_cliente_vendedor_idx` (`codVendedor` ASC),
  INDEX `fk_cliente_cobrador_idx` (`codCobrador` ASC),
  CONSTRAINT `fk_cliente_vendedor`
    FOREIGN KEY (`codVendedor`)
    REFERENCES `sigcodb`.`Personal` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_cobrador`
    FOREIGN KEY (`codCobrador`)
    REFERENCES `sigcodb`.`Personal` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Proveedor` (
  `codigo` VARCHAR(5) NOT NULL,
  `ciRuc` VARCHAR(10) NULL,
  `proveedor` VARCHAR(45) NULL,
  `telefono` VARCHAR(20) NULL,
  `direccion` VARCHAR(45) NULL,
  `codSucursal` VARCHAR(3) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Usuario` (
  `codigo` VARCHAR(5) NOT NULL,
  `Usuario` VARCHAR(45) NULL,
  `Login` VARCHAR(45) NULL,
  `Clave` VARCHAR(45) NULL,
  `codNivel` VARCHAR(5) NULL COMMENT 'nivel de acceso',
  `codPersonal` VARCHAR(5) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Compra` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `nroComprobante` VARCHAR(15) NULL,
  `fecha` DATE NULL,
  `hora` VARCHAR(15) NULL,
  `total` DECIMAL(10,2) NULL,
  `codProveedor` VARCHAR(5) NULL,
  `codUsuario` VARCHAR(5) NULL,
  `codPersonal` VARCHAR(5) NULL,
  `codDeposito` VARCHAR(5) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `tipoCompra` ENUM('CON','CRE') NULL,
  PRIMARY KEY (`idCompra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`DetCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`DetCompra` (
  `idDetCompra` INT NOT NULL AUTO_INCREMENT,
  `idCompra` INT NOT NULL,
  `codArticulo` VARCHAR(10) NULL,
  `precioCosto` DECIMAL(10,2) NULL,
  `iva` INT NULL,
  `cantidad` DECIMAL(10,2) NULL,
  `subtotal` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idDetCompra`),
  INDEX `fk_DetCompra_Compra1_idx` (`idCompra` ASC),
  CONSTRAINT `fk_DetCompra_Compra1`
    FOREIGN KEY (`idCompra`)
    REFERENCES `sigcodb`.`Compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Empresa` (
  `codigo` VARCHAR(5) NOT NULL,
  `empresa` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `nroComprobante` VARCHAR(10) NULL,
  `fecha` DATE NULL,
  `total` DECIMAL(10,2) NULL,
  `tipoVenta` ENUM('CON','CRE') NULL COMMENT ' CON - contado\nCRE - credito',
  `codCliente` VARCHAR(10) NULL,
  `codVendedor` VARCHAR(5) NULL,
  `codUsuario` VARCHAR(5) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `codDeposito` VARCHAR(5) NULL,
  PRIMARY KEY (`idVenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`DetVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`DetVenta` (
  `idDetVenta` INT NOT NULL AUTO_INCREMENT,
  `codArticulo` VARCHAR(10) NULL,
  `cantidad` DECIMAL(10,2) NULL,
  `precioCosto` DECIMAL(10,2) NULL,
  `precioVenta` DECIMAL(10,2) NULL,
  `subtotal` DECIMAL(10,2) NULL,
  `idVenta` INT NOT NULL,
  PRIMARY KEY (`idDetVenta`),
  INDEX `fk_DetVenta_Venta1_idx` (`idVenta` ASC),
  CONSTRAINT `fk_DetVenta_Venta1`
    FOREIGN KEY (`idVenta`)
    REFERENCES `sigcodb`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Sucursal` (
  `codigo` VARCHAR(5) NOT NULL,
  `ruc` VARCHAR(45) NULL,
  `sucursal` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `Telefono` VARCHAR(20) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_sucursal_empresa_idx` (`codEmpresa` ASC),
  CONSTRAINT `fk_sucursal_empresa`
    FOREIGN KEY (`codEmpresa`)
    REFERENCES `sigcodb`.`Empresa` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`MovCaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`MovCaja` (
  `idMovCaja` INT NOT NULL AUTO_INCREMENT,
  `operacion` ENUM('VNT','CMP','DEVC','DEVV','OTR') NULL COMMENT 'VNT - Venta.\nCMP - Compra.\nCOB - Cobros.\nPAG - Pagos.\nDEVC- Devolucion compra.\nDEVV- Devolucion venta.\nOTR - Otros.',
  `fecha` DATE NULL,
  `hora` VARCHAR(15) NULL,
  `tipo` ENUM('I','E') NULL COMMENT 'E - Egreso\nI -Ingreso',
  `codConcepto` VARCHAR(5) NULL,
  `nroCheque` VARCHAR(20) NULL,
  `CodUsuario` VARCHAR(5) NULL,
  `codTipopago` VARCHAR(5) NULL,
  `monto` DECIMAL(10,2) NULL,
  `detalles` VARCHAR(250) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  PRIMARY KEY (`idMovCaja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`MotivoMovInventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`MotivoMovInventario` (
  `codigo` VARCHAR(5) NOT NULL,
  `motivoMovInventario` VARCHAR(45) NULL,
  `tipo` ENUM('E','S') NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Modulo` (
  `codigo` VARCHAR(5) NOT NULL,
  `modulo` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Acceso` (
  `idAcceso` INT NOT NULL AUTO_INCREMENT,
  `actualizar` INT NULL,
  `borrar` INT NULL,
  `nuevo` INT NULL,
  `modificar` INT NULL,
  `acceso` INT NULL,
  `codUsuario` VARCHAR(5) NULL,
  `codNivelAcceso` VARCHAR(5) NULL,
  `codFormulario` VARCHAR(5) NULL,
  `codModulo` VARCHAR(5) NULL,
  PRIMARY KEY (`idAcceso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Acceso` (
  `idAcceso` INT NOT NULL AUTO_INCREMENT,
  `actualizar` INT NULL,
  `borrar` INT NULL,
  `nuevo` INT NULL,
  `modificar` INT NULL,
  `acceso` INT NULL,
  `codUsuario` VARCHAR(5) NULL,
  `codNivelAcceso` VARCHAR(5) NULL,
  `codFormulario` VARCHAR(5) NULL,
  `codModulo` VARCHAR(5) NULL,
  PRIMARY KEY (`idAcceso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`InventarioMov`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`InventarioMov` (
  `idInventarioMov` INT NOT NULL AUTO_INCREMENT,
  `nroMovimiento` VARCHAR(10) NULL,
  `fecha` DATE NULL,
  `hora` VARCHAR(20) NULL,
  `tipo` ENUM('E','S') NULL,
  `codMotivoMov` VARCHAR(5) NULL,
  `codUsuario` VARCHAR(5) NULL,
  `codDeposito` VARCHAR(5) NULL,
  `CodSucursal` VARCHAR(5) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `obs` VARCHAR(100) NULL,
  `total` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idInventarioMov`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`DetInventarioMov`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`DetInventarioMov` (
  `idDetInventarioMov` INT NOT NULL AUTO_INCREMENT,
  `idInventarioMov` INT NOT NULL,
  `codArticulo` VARCHAR(5) NULL,
  `cantidad` DECIMAL(10,2) NULL,
  `precioCosto` DECIMAL(10,2) NULL COMMENT 'precio de costo.',
  PRIMARY KEY (`idDetInventarioMov`),
  INDEX `fk_DetInventarioMov_InventarioMov1_idx` (`idInventarioMov` ASC),
  CONSTRAINT `fk_DetInventarioMov_InventarioMov1`
    FOREIGN KEY (`idInventarioMov`)
    REFERENCES `sigcodb`.`InventarioMov` (`idInventarioMov`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Departamento` (
  `codigo` VARCHAR(5) NOT NULL,
  `departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Ciudad` (
  `codigo` VARCHAR(5) NOT NULL,
  `ciudad` VARCHAR(45) NULL,
  `codDepartamento` VARCHAR(5) NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_ciudad_dpto_idx` (`codDepartamento` ASC),
  CONSTRAINT `fk_ciudad_dpto`
    FOREIGN KEY (`codDepartamento`)
    REFERENCES `sigcodb`.`Departamento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Barrio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Barrio` (
  `codigo` VARCHAR(5) NOT NULL,
  `barrio` VARCHAR(45) NULL,
  `codciudad` VARCHAR(5) NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_barrrio_ciudad_idx` (`codciudad` ASC),
  CONSTRAINT `fk_barrrio_ciudad`
    FOREIGN KEY (`codciudad`)
    REFERENCES `sigcodb`.`Ciudad` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Menu` (
  `codigo` VARCHAR(5) NOT NULL,
  `orden` VARCHAR(5) NULL,
  `key` VARCHAR(5) NULL,
  `parent` VARCHAR(5) NULL,
  `text` VARCHAR(100) NULL,
  `codFormulario` VARCHAR(5) NULL,
  `codModulo` VARCHAR(5) NULL,
  `tipo` INT NULL COMMENT '1 Carpeta 2 formulario',
  INDEX `idxOrden` (`orden` ASC),
  INDEX `idxKey` (`key` ASC),
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Timbrado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Timbrado` (
  `timbrado` VARCHAR(8) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `vto` DATE NULL,
  `nroCompInicial` VARCHAR(15) NULL,
  `nroCompFinal` VARCHAR(15) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Oferta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Oferta` (
  `idOferta` INT NOT NULL AUTO_INCREMENT,
  `nroOferta` VARCHAR(5) NULL,
  `fecha` DATE NULL,
  `fechaDesde` DATE NULL,
  `fechaHasta` DATE NULL,
  `codUsuario` VARCHAR(5) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  PRIMARY KEY (`idOferta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`DetOferta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`DetOferta` (
  `idDetOferta` INT NOT NULL AUTO_INCREMENT,
  `codArticulo` VARCHAR(5) NULL,
  `descuento` DECIMAL(10,2) NULL,
  `idOferta` INT NOT NULL,
  PRIMARY KEY (`idDetOferta`),
  INDEX `fk_DetOferta_Oferta1_idx` (`idOferta` ASC),
  CONSTRAINT `fk_DetOferta_Oferta1`
    FOREIGN KEY (`idOferta`)
    REFERENCES `sigcodb`.`Oferta` (`idOferta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Combo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Combo` (
  `idCombo` INT NOT NULL AUTO_INCREMENT,
  `nroCombo` VARCHAR(5) NULL,
  `Decripcion` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `total` DECIMAL(10,2) NULL,
  `fechaDesde` DATE NULL,
  `fechaHasta` DATE NULL,
  `codUsuario` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  PRIMARY KEY (`idCombo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`DetCombo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`DetCombo` (
  `idDetCombo` INT NOT NULL AUTO_INCREMENT,
  `idCombo` INT NOT NULL,
  `CodArticulo` VARCHAR(5) NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`idDetCombo`),
  INDEX `fk_DetCombo_Combo1_idx` (`idCombo` ASC),
  CONSTRAINT `fk_DetCombo_Combo1`
    FOREIGN KEY (`idCombo`)
    REFERENCES `sigcodb`.`Combo` (`idCombo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Servicio` (
  `idServicio` INT NOT NULL,
  `nroServicion` VARCHAR(5) NULL,
  `idVenta` INT NULL,
  `fechaIngreso` DATE NULL,
  `fechaEntrega` DATE NULL,
  `nroServicio` VARCHAR(5) NULL,
  `codTecnico` VARCHAR(5) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `codArticulo` VARCHAR(45) NULL,
  `costo` DECIMAL(10,2) NULL,
  `entegado` INT NULL DEFAULT 0 COMMENT '1 - entregado',
  `estadoEntrega` VARCHAR(250) NULL COMMENT 'descripcion de como fue entregado el articulo.',
  `diagnProblema` VARCHAR(250) NULL COMMENT 'descripcion de problema encontrado.',
  PRIMARY KEY (`idServicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`PrestamoAriculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`PrestamoAriculo` (
  `idPrestamoAriculo` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `codUsuario` VARCHAR(5) NULL,
  `codCliente` VARCHAR(10) NULL,
  `estado` ENUM('PEN','CAN') NULL,
  `total` DECIMAL(10,2) NULL,
  `tipo` ENUM('REC','OTR') NULL COMMENT 'REC - RECIBIDO\nOTR - OTORGADO',
  `obs` VARCHAR(250) NULL,
  PRIMARY KEY (`idPrestamoAriculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`DetPrestamoArticulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`DetPrestamoArticulo` (
  `idDetPrestamoArticulo` INT NOT NULL AUTO_INCREMENT,
  `idPrestamoAriculo` INT NOT NULL,
  `codArticulo` VARCHAR(5) NULL,
  `precio` DECIMAL(10,2) NULL,
  `cantidad` DECIMAL(10,2) NULL,
  `subtotal` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idDetPrestamoArticulo`),
  INDEX `fk_DetPrestamoArticulo_PrestamoAriculo1_idx` (`idPrestamoAriculo` ASC),
  CONSTRAINT `fk_DetPrestamoArticulo_PrestamoAriculo1`
    FOREIGN KEY (`idPrestamoAriculo`)
    REFERENCES `sigcodb`.`PrestamoAriculo` (`idPrestamoAriculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Cargo` (
  `codigo` VARCHAR(5) NOT NULL,
  `cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Contrato` (
  `idContrato` INT NOT NULL AUTO_INCREMENT,
  `codCargo` VARCHAR(5) NULL,
  `fechainicio` DATE NULL,
  `fechavto` DATE NULL,
  `codUsuario` VARCHAR(5) NULL,
  `codPersonal` VARCHAR(5) NULL,
  `tipoContrato` ENUM('D','I') NULL COMMENT 'tipo de contrato.\nD - contrato definido\nI - contrato indefinido',
  `tipoJornada` ENUM('D','M','S') NULL COMMENT 'D-diaria\nM-Mensual\nS-Semanal',
  `horaJornada` INT NULL,
  `duracionDia` INT NULL COMMENT 'duracion de contrato en dias.',
  `codMotivoFinali` VARCHAR(5) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `estado` ENUM('V','F') NULL COMMENT 'V - vigente\nF - finalizado\nS - Suspendido',
  PRIMARY KEY (`idContrato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Credito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Credito` (
  `idCredito` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(10) NULL,
  `fecha` DATE NULL,
  `primerVto` DATE NULL,
  `entregaInicial` VARCHAR(45) NULL,
  `cantCouta` INT NULL,
  `origen` ENUM('CLI','PRO','PER') NULL COMMENT 'CLI -cliente\nPRO - proveedor\nPER - Personal.',
  `idAdelanto` INT NULL COMMENT 'FK de adelanto',
  `total` DECIMAL(10,2) NULL,
  `saldo` DECIMAL(10,2) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `estado` ENUM('PEN','CAN','ANU') NULL COMMENT 'PEN - pendiente\nCAN - cancelado\nANU - anulado',
  PRIMARY KEY (`idCredito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`SolicitudCredito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`SolicitudCredito` (
  `idSolicitudCredito` INT NOT NULL AUTO_INCREMENT,
  `nroSolicitud` VARCHAR(10) NULL,
  `fecha` DATE NULL,
  `fechaapro` DATE NULL COMMENT 'fecha de aprobacion.',
  `codCliente` VARCHAR(10) NULL,
  `codVendedor` VARCHAR(5) NULL COMMENT 'codigo del vendedor solicitante.',
  `codAprovador` VARCHAR(5) NULL COMMENT 'codigo de encargado de venta que aprobo la solicitud.',
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `combo` INT NULL COMMENT 'codigo de combo.',
  `cantCuota` INT NULL,
  `total` DECIMAL(10,2) NULL,
  `tipoSolicCred` ENUM('N','C') NULL COMMENT 'N- NORMAL\nC- COMBO',
  `nombreCliente` VARCHAR(45) NULL,
  `apellidoCliente` VARCHAR(45) NULL,
  `fechaNac` DATE NULL COMMENT 'fecha de nacimiento del cliente',
  `sexo` ENUM('M','F') NULL,
  `telefonoCliente` VARCHAR(45) NULL,
  `emailCliente` VARCHAR(45) NULL,
  `codPais` VARCHAR(5) NULL,
  `codDpartamento` VARCHAR(5) NULL,
  `codciudad` VARCHAR(5) NULL,
  `codBarrio` VARCHAR(5) NULL,
  `codProfesion` VARCHAR(5) NULL,
  `nroCasa` VARCHAR(5) NULL,
  `referencia_per_nomb1` VARCHAR(45) NULL,
  `referencia_per_nomb2` VARCHAR(45) NULL,
  `referencia_per_nomb3` VARCHAR(45) NULL,
  `referencia_per_tel1` VARCHAR(45) NULL,
  `referencia_per_tel2` VARCHAR(45) NULL,
  `referencia_per_tel3` VARCHAR(45) NULL,
  `estado` ENUM('PEN','APR','ANU') NULL COMMENT 'PEN- pendiente\nAPR -aprobado\nANU - anulado',
  PRIMARY KEY (`idSolicitudCredito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`DetSolicitudCredito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`DetSolicitudCredito` (
  `idDetSolicitudCredito` INT NOT NULL AUTO_INCREMENT,
  `SidSolicitudCredito` INT NOT NULL,
  `codArticulo` VARCHAR(10) NULL,
  `cantidad` INT NULL,
  `precio` DECIMAL(10,2) NULL,
  `subtotal` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idDetSolicitudCredito`),
  INDEX `fk_DetSolicitudCredito_SolicitudCredito1_idx` (`SidSolicitudCredito` ASC),
  CONSTRAINT `fk_DetSolicitudCredito_SolicitudCredito1`
    FOREIGN KEY (`SidSolicitudCredito`)
    REFERENCES `sigcodb`.`SolicitudCredito` (`idSolicitudCredito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`OrdenCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`OrdenCompra` (
  `idOrdenCompra` INT NOT NULL AUTO_INCREMENT,
  `nroOrden` VARCHAR(5) NULL,
  `fechaEmision` DATE NULL,
  `fechaApoba` DATE NULL,
  `codPersonal` VARCHAR(5) NULL,
  `codProveedor` VARCHAR(5) NULL,
  `codUsuario` VARCHAR(5) NULL,
  `gravadas5` DECIMAL(10,2) NULL,
  `gravadas10` DECIMAL(10,2) NULL,
  `iva5` DECIMAL(10,2) NULL,
  `iva10` DECIMAL(10,2) NULL,
  `total` DECIMAL(10,2) NULL,
  `estado` ENUM('PEN','APR') NULL,
  PRIMARY KEY (`idOrdenCompra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`DetOrdenCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`DetOrdenCompra` (
  `idDetOrdenCompra` INT NOT NULL AUTO_INCREMENT,
  `subtotal` DECIMAL(10,2) NULL,
  `precioCosto` DECIMAL(10,2) NULL,
  `iva` INT NULL,
  `cantidad` DECIMAL(10,2) NULL,
  `codArticulo` VARCHAR(10) NULL,
  `idOrdenCompra` INT NOT NULL,
  PRIMARY KEY (`idDetOrdenCompra`),
  INDEX `fk_DetOrdenCompra_OrdenCompra1_idx` (`idOrdenCompra` ASC),
  CONSTRAINT `fk_DetOrdenCompra_OrdenCompra1`
    FOREIGN KEY (`idOrdenCompra`)
    REFERENCES `sigcodb`.`OrdenCompra` (`idOrdenCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`OrdenPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`OrdenPago` (
  `idOrdenPago` INT NOT NULL AUTO_INCREMENT,
  `nroOrden` VARCHAR(5) NULL,
  `fecha` DATE NULL,
  `codProveedor` VARCHAR(5) NULL,
  `codCliente` VARCHAR(10) NULL,
  `codUsuario` VARCHAR(5) NULL,
  `codPersonal` VARCHAR(5) NULL,
  `codTipopago` VARCHAR(5) NULL,
  `codBanco` VARCHAR(5) NULL COMMENT 'en caso de que el pago se a cheque',
  `nroCheque` VARCHAR(20) NULL COMMENT 'numero de cheque en caso de que tipo de pago se a cheque',
  `origen` ENUM('CLI','PRO','PER') NULL COMMENT 'CLI -  clientes\nPRO - proveedor\nPER -  personal',
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `total` DECIMAL(10,2) NULL,
  `idNomina` INT NULL,
  `idCredito` INT NULL,
  `estado` ENUM('PEN','PAG','ANU') NULL DEFAULT 'PEN' COMMENT 'PEN - pendiente\nPAG - pagado\nANU -anulado',
  PRIMARY KEY (`idOrdenPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`TipoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`TipoPago` (
  `Codigo` VARCHAR(5) NOT NULL,
  `Tipopago` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`DetOrdenPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`DetOrdenPago` (
  `idDetOrdenPago` INT NOT NULL AUTO_INCREMENT,
  `idOrdenPago` INT NOT NULL,
  `idCredito` INT NULL,
  `orden` INT NULL,
  `codConcepto` VARCHAR(5) NULL COMMENT 'Si Origen en la tabla OrdenPago es \'PER\', entonces este campo contendra los codigo del concepto de retribucion tablas \'ConceptoRetribucion\'.',
  `monto` DECIMAL(10,2) NULL,
  `porcent` DECIMAL(10,2) NULL COMMENT 'contendra valores de porcentaje que puedan venir adjuntado de cualquier indole.',
  PRIMARY KEY (`idDetOrdenPago`),
  INDEX `fk_DetOrdenPago_OrdenPago1_idx` (`idOrdenPago` ASC),
  CONSTRAINT `fk_DetOrdenPago_OrdenPago1`
    FOREIGN KEY (`idOrdenPago`)
    REFERENCES `sigcodb`.`OrdenPago` (`idOrdenPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`DetCredito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`DetCredito` (
  `idDetCredito` INT NOT NULL AUTO_INCREMENT,
  `idCredito` INT NOT NULL,
  `orden` INT NULL,
  `fecvto` DATE NULL,
  `diaAtraso` INT NULL,
  `fechaPago` DATE NULL,
  `monto` DECIMAL(10,2) NULL,
  `importe` DECIMAL(10,2) NULL,
  `saldo` DECIMAL(10,2) NULL,
  `estado` ENUM('PEN','CAN') NULL,
  PRIMARY KEY (`idDetCredito`),
  INDEX `fk_DetCredito_Credito1_idx` (`idCredito` ASC),
  CONSTRAINT `fk_DetCredito_Credito1`
    FOREIGN KEY (`idCredito`)
    REFERENCES `sigcodb`.`Credito` (`idCredito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Banco` (
  `codigo` VARCHAR(5) NOT NULL,
  `banco` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`RendRecibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`RendRecibo` (
  `idRendRecibo` INT NOT NULL AUTO_INCREMENT,
  `nroRendicion` VARCHAR(10) NULL,
  `nroRecibo` VARCHAR(15) NULL,
  `fechaAlta` DATE NULL,
  `fechaProc` DATE NULL COMMENT 'fecha de procesado.',
  `codCobrador` VARCHAR(5) NULL,
  `codCliente` VARCHAR(10) NULL,
  `codTipopago` VARCHAR(5) NULL,
  `nroCheque` VARCHAR(20) NULL,
  `total` DECIMAL(10,2) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `idCredito` INT NULL,
  `estado` ENUM('PEN','PRO','ANU') NULL COMMENT 'PEN -pendiente\nPRO -procesado\nANU -anulado ',
  PRIMARY KEY (`idRendRecibo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`PagoCob`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`PagoCob` (
  `idPagoCob` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `nroRecibo` VARCHAR(15) NULL,
  `tipo` ENUM('CB','PG') NULL COMMENT 'CB - cobro\nPG - pago',
  `codCliente` VARCHAR(10) NULL,
  `codProveedor` VARCHAR(5) NULL,
  `codCobrador` VARCHAR(5) NULL,
  `codPersonal` VARCHAR(5) NULL,
  `codTipopago` VARCHAR(5) NULL,
  `nroCheque` VARCHAR(20) NULL,
  `total` DECIMAL(10,2) NULL,
  `origen` ENUM('CLI','PRO','PER') NULL COMMENT 'origen de pago.\nCLI- Cliente.\nPRO- Proveedor.\nPER. - Personal.',
  `idRendicion` INT NULL COMMENT 'referencia a la rendicion de cobrador',
  `idCompra` INT NULL COMMENT 'referencia a la compra.',
  `idVenta` INT NULL,
  `idCredito` INT NULL,
  `idOrdenPago` INT NULL,
  `idNomina` INT NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `estado` ENUM('PAG','ANU') NULL COMMENT 'PAG - Pagado\nANU - Anulado',
  PRIMARY KEY (`idPagoCob`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`DetPagoCob`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`DetPagoCob` (
  `idDetPagoCob` INT NOT NULL AUTO_INCREMENT,
  `idPagoCob` INT NOT NULL,
  `idCredito` INT NULL,
  `orden` INT NULL,
  `codConcepto` VARCHAR(5) NULL,
  `monto` DECIMAL(10,2) NULL,
  `interes` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idDetPagoCob`),
  INDEX `fk_DetPagoCob_PagoCob1_idx` (`idPagoCob` ASC),
  CONSTRAINT `fk_DetPagoCob_PagoCob1`
    FOREIGN KEY (`idPagoCob`)
    REFERENCES `sigcodb`.`PagoCob` (`idPagoCob`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`DetRend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`DetRend` (
  `idDetRendRecibo` INT NOT NULL AUTO_INCREMENT,
  `idRendRecibo` INT NOT NULL,
  `idRendicion` INT NULL,
  `orden` INT NULL,
  `codConcepto` VARCHAR(5) NULL,
  `monto` VARCHAR(45) NULL,
  `interes` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idDetRendRecibo`),
  INDEX `fk_DetRend_RendRecibo1_idx` (`idRendRecibo` ASC),
  CONSTRAINT `fk_DetRend_RendRecibo1`
    FOREIGN KEY (`idRendRecibo`)
    REFERENCES `sigcodb`.`RendRecibo` (`idRendRecibo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Cuenta` (
  `idCuenta` INT NOT NULL AUTO_INCREMENT,
  `nroCuenta` VARCHAR(10) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucusal` VARCHAR(5) NULL,
  `fechaApe` DATE NULL,
  `saldoActual` DECIMAL(10,2) NULL,
  `saldoMinimo` DECIMAL(10,2) NULL,
  `codBanco` VARCHAR(5) NULL,
  `descripcioncta` VARCHAR(45) NULL,
  `tipo` ENUM('CC','CA') NULL COMMENT 'CC - CUENTA CORRIENTE\nCA - CAJA AHORRO',
  PRIMARY KEY (`idCuenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Cheque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Cheque` (
  `idCheque` INT NOT NULL AUTO_INCREMENT,
  `nroCheque` VARCHAR(10) NULL,
  `codbeneficiario` VARCHAR(5) NULL,
  `codBanco` VARCHAR(5) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `fechaEmision` DATE NULL,
  `fechaRecepcion` DATE NULL,
  `origen` ENUM('VNT','CMP','OTR') NULL COMMENT 'VNT - venta\nCMP - compra\nOTR  otros',
  `monto` DECIMAL(10,2) NULL,
  `estado` ENUM('PEN','COB','DEP','ANU') NULL COMMENT 'PEN - PENDIENTE\nCOB- COBRADOR\nDEP - DEPOSITADO\nANU -ANULADO\n',
  `detalle` VARCHAR(45) NULL,
  `tipo` ENUM('CB','PG') NULL COMMENT 'CB - Cobro\nPG - Pago',
  `tipoBenef` ENUM('CLI','PRO','PER','EMP') NULL COMMENT 'CLI - Cliente\nPRO - Proveedor\nPER - Personal\nEMP - Empresa',
  PRIMARY KEY (`idCheque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Boleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Boleta` (
  `idBoleta` INT NOT NULL,
  `nroBoleta` VARCHAR(10) NULL,
  `codBanco` VARCHAR(5) NULL,
  `nroCuenta` VARCHAR(20) NULL,
  `codPersonal` VARCHAR(5) NULL,
  `serie` CHAR(1) NULL,
  `fecha` DATE NULL,
  `tipoCuenta` ENUM('CC','CA') NULL,
  `tipoBoleta` ENUM('DEP','EXT') NULL COMMENT 'DEP - deposito\nEXT - Extraccion\n',
  `totalImporte` DECIMAL(10,2) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  PRIMARY KEY (`idBoleta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`DetBoleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`DetBoleta` (
  `idDetBoleta` INT NOT NULL AUTO_INCREMENT,
  `nroChequre` VARCHAR(10) NULL,
  `importe` DECIMAL(10,2) NULL,
  `tipo` ENUM('EFE','CHQ') NULL COMMENT 'EFE -EFECTIVO\nCHQ -CHEQUE',
  `idBoleta` INT NOT NULL,
  PRIMARY KEY (`idDetBoleta`),
  INDEX `fk_DetBoleta_Boleta1_idx` (`idBoleta` ASC),
  CONSTRAINT `fk_DetBoleta_Boleta1`
    FOREIGN KEY (`idBoleta`)
    REFERENCES `sigcodb`.`Boleta` (`idBoleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`MovBancario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`MovBancario` (
  `idMovBancario` INT NOT NULL,
  `nroMovBancario` VARCHAR(5) NULL,
  `fecha` DATE NULL,
  `codBanco` VARCHAR(5) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `nroCuenta` VARCHAR(10) NULL,
  `nroComprobante` VARCHAR(10) NULL,
  `codPersonal` VARCHAR(5) NULL COMMENT 'personal que realizo la operacion',
  `codConcepto` VARCHAR(5) NULL,
  `importe` DECIMAL(10,2) NULL,
  `tipoComp` ENUM('BOL','CHQ') NULL COMMENT 'tipo de comprobante\nBOL - BOLETA\nCHQ - CHEQUE\n',
  `tipoMov` ENUM('D','C') NULL COMMENT 'D- Debito(-)\nC- Credito(+)',
  PRIMARY KEY (`idMovBancario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Transferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Transferencia` (
  `idTransferencia` INT NOT NULL AUTO_INCREMENT,
  `nroTransferecia` VARCHAR(5) NULL,
  `codConcepto` VARCHAR(5) NULL,
  `nroCuenta` VARCHAR(10) NULL,
  `fecha` DATE NULL,
  `importe` DECIMAL(10,2) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `obs` VARCHAR(45) NULL,
  PRIMARY KEY (`idTransferencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`cuentaTercero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`cuentaTercero` (
  `idcuentaTercero` INT NOT NULL AUTO_INCREMENT,
  `nroCuenta` VARCHAR(10) NULL,
  `titular` VARCHAR(45) NULL,
  `ciRuc` VARCHAR(10) NULL,
  `codBanco` VARCHAR(5) NULL,
  `tipoCuenta` ENUM('PRO','CLI','EMP') NULL,
  `codTitular` VARCHAR(5) NULL,
  PRIMARY KEY (`idcuentaTercero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`referencia` (
  `idReferencia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `contacto` VARCHAR(45) NULL,
  `codCliente` VARCHAR(10) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  PRIMARY KEY (`idReferencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Amonestacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Amonestacion` (
  `idAmonestacion` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `codMotAmo` VARCHAR(5) NULL,
  `codPersonal` VARCHAR(5) NULL,
  `descuento` DECIMAL(10,2) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `obs` VARCHAR(100) NULL,
  PRIMARY KEY (`idAmonestacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`MotivoAmonetacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`MotivoAmonetacion` (
  `codigo` VARCHAR(5) NOT NULL,
  `motivo` VARCHAR(45) NULL,
  `codConceptoRetri` VARCHAR(5) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`PromesaPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`PromesaPago` (
  `idPromesa` INT NOT NULL,
  `fecha` DATE NULL,
  `monto` DECIMAL(10,2) NULL,
  `codCliente` VARCHAR(5) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `obs` VARCHAR(250) NULL,
  PRIMARY KEY (`idPromesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Sorteo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Sorteo` (
  `idSorteo` INT NOT NULL,
  `fechaSorteo` DATE NULL,
  `estado` VARCHAR(45) NULL,
  `fechaDesde` DATE NULL,
  `fechaHasta` DATE NULL,
  `codcliente` VARCHAR(5) NULL,
  `retirado` INT NULL COMMENT '1 retirado',
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  PRIMARY KEY (`idSorteo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`premios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`premios` (
  `idpremios` INT NOT NULL AUTO_INCREMENT,
  `idSorteo` INT NOT NULL,
  `tipoPremio` ENUM('ART','EFE') NULL,
  `codArticulo` VARCHAR(5) NULL,
  `cantArticulo` INT NULL,
  `monto` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idpremios`),
  INDEX `fk_premios_Sorteo1_idx` (`idSorteo` ASC),
  CONSTRAINT `fk_premios_Sorteo1`
    FOREIGN KEY (`idSorteo`)
    REFERENCES `sigcodb`.`Sorteo` (`idSorteo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Vacacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Vacacion` (
  `idVacacion` INT NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATE NULL,
  `fechaFin` DATE NULL,
  `fechaAbono` DATE NULL,
  `periodo` INT NULL,
  `codPersonal` VARCHAR(5) NULL,
  `jornales` DECIMAL(10,2) NULL,
  `monto` DECIMAL(10,2) NULL COMMENT 'monto pagado por vacacion jornales * cantidad de dias trabajadas',
  `diasVaca` INT NULL COMMENT 'dias de vacasiones',
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `usado` INT NULL DEFAULT 0 COMMENT '1 usado',
  PRIMARY KEY (`idVacacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`conceptoRetribucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`conceptoRetribucion` (
  `codigo` VARCHAR(5) NOT NULL,
  `concepto` VARCHAR(45) NULL,
  `conceptode` ENUM('A','D') NULL COMMENT 'A- Abono\nD- Descuento',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`concepto_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`concepto_cargo` (
  `idconcepto_cargo` INT NOT NULL,
  `codConceptoRetri` VARCHAR(5) NULL,
  `codCargo` VARCHAR(45) NULL,
  `importe` DECIMAL(10,2) NULL,
  `porcentaje` DECIMAL(10,2) NULL,
  `calcPorcentaje` INT NULL DEFAULT 0 COMMENT 'campo para establecer que se utilizara un porcentaje.\n1 usar calculo en base a porcentajes.',
  PRIMARY KEY (`idconcepto_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Retribucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Retribucion` (
  `idRetribucion` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `mes` INT NULL,
  `periodo` INT NULL,
  `codPersonal` VARCHAR(5) NULL,
  `codConceptoRetri` VARCHAR(5) NULL,
  `fDevengoDesde` DATE NULL,
  `fDevengoHasta` DATE NULL,
  `devengaFecha` INT NULL,
  `tipoRetri` ENUM('NOR','ADE','VAC') NULL COMMENT 'NOR - Normal\nADE - Adelanto\nVAC - Vacacion',
  `codEmpesa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `total` DECIMAL(10,2) NULL,
  `idRef` INT NULL COMMENT 'id de referencia segun el tipo de retribucion: adelantos, vacaciones,amonestaciones.',
  `obs` VARCHAR(50) NULL,
  PRIMARY KEY (`idRetribucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`EstiContrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`EstiContrato` (
  `idEstiContrato` INT NOT NULL AUTO_INCREMENT,
  `idContrato` INT NOT NULL,
  `codEstipulacion` VARCHAR(5) NULL,
  `textoadicional` VARCHAR(250) NULL,
  PRIMARY KEY (`idEstiContrato`),
  INDEX `fk_EstiContrato_Contrato1_idx` (`idContrato` ASC),
  CONSTRAINT `fk_EstiContrato_Contrato1`
    FOREIGN KEY (`idContrato`)
    REFERENCES `sigcodb`.`Contrato` (`idContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Estipulacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Estipulacion` (
  `codigo` VARCHAR(5) NOT NULL,
  `Estipulacion` VARCHAR(250) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Nomina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Nomina` (
  `idNomina` INT NOT NULL AUTO_INCREMENT,
  `idContrato` INT NOT NULL,
  `fechaEmision` DATE NULL,
  `mes` INT NULL,
  `periodo` INT NULL COMMENT 'año de la nomina',
  `codPersonal` VARCHAR(5) NULL,
  `codCargo` VARCHAR(5) NULL,
  `devengo` DECIMAL(10,2) NULL COMMENT 'la suma de todos los salarios',
  `deduccion` DECIMAL(10,2) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `total` DECIMAL(10,2) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `cerrado` INT NULL DEFAULT 0 COMMENT '1 cerrado ya no se podra utilizar',
  PRIMARY KEY (`idNomina`),
  INDEX `fk_Nomina_Contrato1_idx` (`idContrato` ASC),
  CONSTRAINT `fk_Nomina_Contrato1`
    FOREIGN KEY (`idContrato`)
    REFERENCES `sigcodb`.`Contrato` (`idContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`DetNomina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`DetNomina` (
  `idDetNomina` INT NOT NULL AUTO_INCREMENT,
  `idNomina` INT NOT NULL,
  `CodConceptoRetri` VARCHAR(5) NULL,
  `conceptoDe` ENUM('A','D') NULL,
  `porcentaje` DECIMAL(10,2) NULL,
  `importe` DECIMAL(10,2) NULL,
  `pagado` INT NULL DEFAULT 0 COMMENT '1',
  `orden` INT NULL COMMENT 'orden de cuota en adelantos',
  PRIMARY KEY (`idDetNomina`),
  INDEX `fk_DetNomina_Nomina1_idx` (`idNomina` ASC),
  CONSTRAINT `fk_DetNomina_Nomina1`
    FOREIGN KEY (`idNomina`)
    REFERENCES `sigcodb`.`Nomina` (`idNomina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Profesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Profesion` (
  `codigo` VARCHAR(5) NOT NULL,
  `Profesion` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Pais` (
  `Codigo` VARCHAR(5) NOT NULL,
  `Pais` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`DetRetribucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`DetRetribucion` (
  `idDetRetribucion` INT NOT NULL AUTO_INCREMENT,
  `idRetribucion` INT NOT NULL,
  `codConceptoRetri` VARCHAR(5) NULL,
  `importe` DECIMAL(10,2) NULL,
  `porcentaje` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idDetRetribucion`),
  INDEX `fk_DetRetribucion_Retribucion1_idx` (`idRetribucion` ASC),
  CONSTRAINT `fk_DetRetribucion_Retribucion1`
    FOREIGN KEY (`idRetribucion`)
    REFERENCES `sigcodb`.`Retribucion` (`idRetribucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`ParametroRRHH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`ParametroRRHH` (
  `idParametro` INT NOT NULL AUTO_INCREMENT,
  `concepAdelanto` VARCHAR(5) NULL,
  `concepVacacion` VARCHAR(5) NULL,
  `porcAdelMax` DECIMAL(10,2) NULL COMMENT 'porcentaje maximo de adelantos sobre salario',
  `porcComiVen` DECIMAL(10,2) NULL COMMENT 'comision base de venta',
  `porcComiCob` DECIMAL(10,2) NULL COMMENT 'comision base cobranza',
  `salarioBase` DECIMAL(10,2) NULL COMMENT 'salario base vigente.',
  PRIMARY KEY (`idParametro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Preaviso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Preaviso` (
  `idPreaviso` INT NOT NULL AUTO_INCREMENT,
  `fechaEmision` DATE NULL,
  `fechaInicio` DATE NULL,
  `fechaFin` DATE NULL,
  `origen` INT NULL COMMENT '1 - empleado 2 - empleado',
  `codPersonal` VARCHAR(5) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `antiguedad` INT NULL,
  PRIMARY KEY (`idPreaviso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Adelanto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Adelanto` (
  `idAdelanto` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL,
  `codPersonal` VARCHAR(5) NULL,
  `monto` DECIMAL(10,2) NULL,
  `estado` ENUM('PEN','CAN') NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codSucursal` VARCHAR(5) NULL,
  `obs` VARCHAR(250) NULL,
  PRIMARY KEY (`idAdelanto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`MotivoFinalizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`MotivoFinalizacion` (
  `codigo` VARCHAR(5) NULL,
  `motivo` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`ParametroVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`ParametroVenta` (
  `idParametroVenta` INT NOT NULL AUTO_INCREMENT,
  `concepVenta` VARCHAR(5) NULL,
  `concepCobro` VARCHAR(5) NULL,
  `concepPago` VARCHAR(5) NULL,
  `codClienteDefault` VARCHAR(5) NULL COMMENT 'cliente por defecto en venta',
  `codDepositoDefault` VARCHAR(5) NULL COMMENT 'codDeposot',
  PRIMARY KEY (`idParametroVenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Zona` (
  `codigo` VARCHAR(5) NOT NULL,
  `zona` VARCHAR(45) NULL,
  `codCiudad` VARCHAR(5) NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_zona_ciudad_idx` (`codCiudad` ASC),
  CONSTRAINT `fk_zona_ciudad`
    FOREIGN KEY (`codCiudad`)
    REFERENCES `sigcodb`.`Ciudad` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Nivel` (
  `codigo` VARCHAR(5) NOT NULL,
  `nivel` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`Deposito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`Deposito` (
  `codigo` VARCHAR(5) NOT NULL,
  `deposito` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`existencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`existencia` (
  `idexistencia` INT NOT NULL AUTO_INCREMENT,
  `stock` INT NULL,
  `stockMinimo` INT NULL,
  `codSucursal` VARCHAR(5) NULL,
  `codEmpresa` VARCHAR(5) NULL,
  `codArticulo` VARCHAR(5) NULL,
  `codDeposito` VARCHAR(5) NULL,
  PRIMARY KEY (`idexistencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigcodb`.`cargo_personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcodb`.`cargo_personal` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `codCargo` VARCHAR(5) NULL,
  `codPersonal` VARCHAR(10) NULL,
  `fecha_alta` DATE NULL,
  `fecha_baja` DATE NULL,
  `estado` ENUM('A', 'I') NULL COMMENT 'A = activo\nb= inactivo',
  PRIMARY KEY (`codigo`),
  INDEX `fk_Cargo_has_Personal_Personal1_idx` (`codPersonal` ASC),
  INDEX `fk_Cargo_has_Personal_Cargo1_idx` (`codCargo` ASC),
  CONSTRAINT `fk_Cargo_has_Personal_Cargo1`
    FOREIGN KEY (`codCargo`)
    REFERENCES `sigcodb`.`Cargo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargo_has_Personal_Personal1`
    FOREIGN KEY (`codPersonal`)
    REFERENCES `sigcodb`.`Personal` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
